name: "Eron Raines"
output_dir: "."
navbar:
  title: "Christie's Website"
  left:
    - text: "Home"
      href: index.html
    - text: "About"
      href: about.html
output:
  html_document:
    theme: paper
    css: 'styles.css'
