theme: jekyll-theme-minimal
name: "Eron Raines"
output_dir: "."
navbar:
  title: "Eron Raines"
  left:
    - text: "Writing"
      href: research.html
    - text: "Speaking"
      href: talks.html
    - text: "Programming"
      href: software.html
    - text: "Teaching"
      href: teaching.html
  right:
    - icon: fa-envelope fa-lg
      href: contact.html
    - icon: fa-github fa-lg
      href: http://github.com/zabore
    - icon: fa-twitter fa-lg
      href: https://twitter.com/zabormetrics

output:
  html_document:
    theme: paper
    css: 'styles.css'
